### ISSUE TITLE
Unable to generate tag from a repository without previous tag

### ISSUE THREAD

**Issue by weslleyss12** [escaletech/releaser#1]
### Describe the bug

When you run the `tag-and-push` script on a repository without any previous tag/release, the script is unable to generate the initial version. 

### Steps to reproduce

1. Create or use any Github repository that doesn't have any tag/release
2. Run the `tag-and-push` script

### Expected behavior

1. Read all repository commits since the first one
2. Show all the changes since repository creation
3. Show the new SemVer number base on commits messages, or suggest a first version when there's no previous

### Actual behavior

* Don't show any change
* Suggest a tag without SemVer
![image](https://user-images.githubusercontent.com/8439154/86269784-a247d700-bba0-11ea-8029-27427cea760d.png)

**Comment by rdumont** [comment]
Yikes, this is a nasty bug. Let's fix it.

According to the SemVer spec, it is [recommended to start at 0.1.0](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase), so we should adopt that as the initial version.
